const FETCHING_MOVIE = 'FETCHING_MOVIE';
const FETCHING_MAIN_MOVIE_SUCCESS = 'FETCHING_MAIN_MOVIE_SUCCESS';
const FETCHING_MAIN_MOVIE_FAILURE = 'FETCHING_MAIN_MOVIE_FAILURE';

const FETCHING_TRENDING = 'FETCHING_TRENDING';
const FETCHING_TRENDING_SUCCESS = 'FETCHING_TRENDING_SUCCESS';
const FETCHING_TRENDING_FAILURE = 'FETCHING_TRENDING_FAILURE';

const FETCHING_ACTION_ADVENTURE = 'FETCHING_ACTION_ADVENTURE';
const FETCHING_ACTION_ADVENTURE_SUCCESS = 'FETCHING_ACTION_ADVENTURE_SUCCESS';
const FETCHING_ACTION_ADVENTURE_FAILURE = 'FETCHING_ACTION_ADVENTURE_FAILURE';

const FETCHING_COMEDIES = 'FETCHING_COMEDIES';
const FETCHING_COMEDIES_SUCCESS = 'FETCHING_COMEDIES_SUCCESS';
const FETCHING_COMEDIES_FAILURE = 'FETCHING_COMEDIES_FAILURE';

const FETCHING_DOCUMENTARIES = 'FETCHING_DOCUMENTARIES';
const FETCHING_DOCUMENTARIES_SUCCESS = 'FETCHING_DOCUMENTARIES_SUCCESS';
const FETCHING_DOCUMENTARIES_FAILURE = 'FETCHING_DOCUMENTARIES_FAILURE';

const FETCHING_DRAMAS = 'FETCHING_DRAMAS';
const FETCHING_DRAMAS_SUCCESS = 'FETCHING_DRAMAS_SUCCESS';
const FETCHING_DRAMAS_FAILURE = 'FETCHING_DRAMAS_FAILURE';

const FETCHING_HORROR = 'FETCHING_HORROR';
const FETCHING_HORROR_SUCCESS = 'FETCHING_HORROR_SUCCESS';
const FETCHING_HORROR_FAILURE = 'FETCHING_HORROR_FAILURE';

const FETCHING_ROMANCE = 'FETCHING_ROMANCE';
const FETCHING_ROMANCE_SUCCESS = 'FETCHING_ROMANCE_SUCCESS';
const FETCHING_ROMANCE_FAILURE = 'FETCHING_ROMANCE_FAILURE';

const FETCHING_SCIFI = 'FETCHING_SCIFI';
const FETCHING_SCIFI_SUCCESS = 'FETCHING_SCIFI_SUCCESS';
const FETCHING_SCIFI_FAILURE = 'FETCHING_SCIFI_FAILURE';

const FETCHING_THRILLER = 'FETCHING_THRILLER';
const FETCHING_THRILLER_SUCCESS = 'FETCHING_THRILLER_SUCCESS';
const FETCHING_THRILLER_FAILURE = 'FETCHING_THRILLER_FAILURE';

const FETCHING_SINGLE_FILM = 'FETCHING_SINGLE_FILM';
const FETCHING_SINGLE_FILM_SUCCESS = 'FETCHING_SINGLE_FILM_SUCCESS';
const FETCHING_SINGLE_FILM_FAILURE = 'FETCHING_SINGLE_FILM_FAILURE';

const FETCHING_TRAILERS = 'FETCHING_TRAILERS';
const FETCHING_TRAILERS_SUCCESS = 'FETCHING_TRAILERS_SUCCESS';
const FETCHING_TRAILER_FAILURE = 'FETCHING_TRAILER_FAILURE';

const FETCHING_SEARCH = 'FETCHING_SEARCH';
const FETCHING_SEARCH_SUCCESS = 'FETCHING_SEARCH_SUCCESS';
const FETCHING_SEARCH_FAILURE = 'FETCHING_SEARCH_FAILURE';
